-- Seed: Catálogo de Produtos do Supermercado
-- Execute no Supabase Dashboard → SQL Editor

INSERT INTO product_catalog (nome_produto, categoria) VALUES
-- Mercearia
('Arroz', 'Mercearia'),
('Feijão', 'Mercearia'),
('Macarrão', 'Mercearia'),
('Farinha de trigo', 'Mercearia'),
('Farinha de mandioca', 'Mercearia'),
('Açúcar', 'Mercearia'),
('Sal', 'Mercearia'),
('Óleo de soja', 'Mercearia'),
('Azeite de oliva', 'Mercearia'),
('Café', 'Mercearia'),
('Achocolatado', 'Mercearia'),
('Leite condensado', 'Mercearia'),
('Creme de leite', 'Mercearia'),
('Molho de tomate', 'Mercearia'),
('Milho em conserva', 'Mercearia'),
('Ervilha em conserva', 'Mercearia'),
('Atum em lata', 'Mercearia'),
('Sardinha em lata', 'Mercearia'),
('Aveia', 'Mercearia'),
('Granola', 'Mercearia'),
('Biscoito cream cracker', 'Mercearia'),
('Biscoito recheado', 'Mercearia'),
('Cereal matinal', 'Mercearia'),
('Gelatina', 'Mercearia'),
('Amendoim', 'Mercearia'),
('Pipoca', 'Mercearia'),
('Vinagre', 'Mercearia'),
('Amido de milho', 'Mercearia'),
-- Laticínios
('Leite integral', 'Laticínios'),
('Leite desnatado', 'Laticínios'),
('Iogurte natural', 'Laticínios'),
('Iogurte grego', 'Laticínios'),
('Bebida láctea', 'Laticínios'),
('Manteiga', 'Laticínios'),
('Margarina', 'Laticínios'),
('Requeijão', 'Laticínios'),
('Cream cheese', 'Laticínios'),
('Leite em pó', 'Laticínios'),
('Creme de leite fresco', 'Laticínios'),
('Nata', 'Laticínios'),
-- Frios
('Queijo mussarela', 'Frios'),
('Queijo prato', 'Frios'),
('Queijo minas', 'Frios'),
('Queijo parmesão', 'Frios'),
('Presunto', 'Frios'),
('Mortadela', 'Frios'),
('Peito de peru', 'Frios'),
('Salame', 'Frios'),
('Apresuntado', 'Frios'),
('Queijo coalho', 'Frios'),
-- Carnes
('Frango inteiro', 'Carnes'),
('Peito de frango', 'Carnes'),
('Coxa e sobrecoxa', 'Carnes'),
('Carne moída', 'Carnes'),
('Alcatra', 'Carnes'),
('Picanha', 'Carnes'),
('Costela', 'Carnes'),
('Linguiça', 'Carnes'),
('Salsicha', 'Carnes'),
('Bacon', 'Carnes'),
('Carne de porco', 'Carnes'),
('Filé de peixe', 'Carnes'),
-- Hortifrúti
('Banana', 'Hortifrúti'),
('Maçã', 'Hortifrúti'),
('Laranja', 'Hortifrúti'),
('Limão', 'Hortifrúti'),
('Manga', 'Hortifrúti'),
('Uva', 'Hortifrúti'),
('Mamão', 'Hortifrúti'),
('Melancia', 'Hortifrúti'),
('Abacaxi', 'Hortifrúti'),
('Morango', 'Hortifrúti'),
('Tomate', 'Hortifrúti'),
('Cebola', 'Hortifrúti'),
('Alho', 'Hortifrúti'),
('Batata', 'Hortifrúti'),
('Cenoura', 'Hortifrúti'),
('Alface', 'Hortifrúti'),
('Brócolis', 'Hortifrúti'),
('Couve', 'Hortifrúti'),
('Pepino', 'Hortifrúti'),
('Pimentão', 'Hortifrúti'),
-- Padaria
('Pão francês', 'Padaria'),
('Pão de forma', 'Padaria'),
('Pão integral', 'Padaria'),
('Bolo pronto', 'Padaria'),
('Torrada', 'Padaria'),
('Bisnaguinha', 'Padaria'),
('Pão de queijo', 'Padaria'),
('Croissant', 'Padaria'),
-- Bebidas
('Água mineral', 'Bebidas'),
('Refrigerante', 'Bebidas'),
('Suco de caixinha', 'Bebidas'),
('Suco natural', 'Bebidas'),
('Chá gelado', 'Bebidas'),
('Cerveja', 'Bebidas'),
('Vinho', 'Bebidas'),
('Energético', 'Bebidas'),
('Água de coco', 'Bebidas'),
('Isotônico', 'Bebidas'),
('Refrigerante zero', 'Bebidas'),
('Chá sachê', 'Bebidas'),
-- Limpeza
('Detergente', 'Limpeza'),
('Sabão em pó', 'Limpeza'),
('Sabão líquido', 'Limpeza'),
('Amaciante', 'Limpeza'),
('Água sanitária', 'Limpeza'),
('Desinfetante', 'Limpeza'),
('Esponja', 'Limpeza'),
('Papel toalha', 'Limpeza'),
('Saco de lixo', 'Limpeza'),
('Limpador multiuso', 'Limpeza'),
('Álcool', 'Limpeza'),
('Pano de chão', 'Limpeza'),
('Lustra móveis', 'Limpeza'),
('Limpa vidros', 'Limpeza'),
-- Higiene
('Papel higiênico', 'Higiene'),
('Sabonete', 'Higiene'),
('Shampoo', 'Higiene'),
('Condicionador', 'Higiene'),
('Creme dental', 'Higiene'),
('Escova de dente', 'Higiene'),
('Desodorante', 'Higiene'),
('Absorvente', 'Higiene'),
('Fralda descartável', 'Higiene'),
('Algodão', 'Higiene'),
('Hastes flexíveis', 'Higiene'),
('Protetor solar', 'Higiene'),
('Creme hidratante', 'Higiene'),
('Lâmina de barbear', 'Higiene'),
-- Congelados
('Pizza congelada', 'Congelados'),
('Lasanha congelada', 'Congelados'),
('Hambúrguer', 'Congelados'),
('Nuggets', 'Congelados'),
('Batata frita congelada', 'Congelados'),
('Sorvete', 'Congelados'),
('Açaí', 'Congelados'),
('Polpa de frutas', 'Congelados'),
-- Temperos
('Pimenta do reino', 'Temperos'),
('Colorau', 'Temperos'),
('Orégano', 'Temperos'),
('Salsinha desidratada', 'Temperos'),
('Cominho', 'Temperos'),
('Tempero pronto', 'Temperos'),
('Caldo de galinha', 'Temperos'),
('Canela', 'Temperos'),
('Louro', 'Temperos'),
('Curry', 'Temperos'),
-- Petshop
('Ração para cachorro', 'Petshop'),
('Ração para gato', 'Petshop'),
('Areia para gato', 'Petshop'),
('Petisco para cachorro', 'Petshop'),
('Sachê para gato', 'Petshop'),
('Antipulgas', 'Petshop');
